# Generated by Django 4.2.2 on 2024-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TF_IDF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='tf-idf/%Y/%m/%d', verbose_name='File'),
        ),
    ]
