# Generated by Django 4.2.11 on 2024-04-19 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsAndTasks', '0002_project_url_readme_alter_project_url_git'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url_readme',
        ),
        migrations.AddField(
            model_name='project',
            name='readme',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='README.md'),
            preserve_default=False,
        ),
    ]
