# Generated by Django 4.2.11 on 2024-04-19 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsAndTasks', '0003_remove_project_url_readme_project_readme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.AddField(
            model_name='task',
            name='readme',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='README.md'),
            preserve_default=False,
        ),
    ]
