# Generated by Django 4.2.2 on 2024-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsAndTasks', '0006_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_from_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Url')),
                ('url_git', models.URLField(verbose_name='Url GitHub')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('readme', models.TextField(verbose_name='README.md')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
            },
        ),
    ]
