# Generated by Django 4.2.11 on 2024-04-19 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsAndTasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_readme',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Url README.md'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='url_git',
            field=models.URLField(verbose_name='Url GitHub'),
        ),
    ]
