# Generated by Django 4.2.11 on 2024-04-19 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsAndTasks', '0005_remove_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
